### PR TITLE
Improve Landing Page

### LINKED ISSUE #12: Improve Landing Page
+ landing page - scroll down to about page and sideways scrolling to about page and sponsor page.
+ background will have animation of constellations ( particle.js ).

### PR DESCRIPTION
**Pull request by Prerna-0202**
Fixes #12 

Screenshots:

https://user-images.githubusercontent.com/76155456/184472736-7dd427ff-67f2-43a1-8387-9078d04e2e60.mov

### CODE REVIEW

**Review by pulkit-30 — APPROVED** [review]

**Comment by dewank07** [comment]
cool !! make the upper navbar white #D9D9D9

**Comment by Prerna-0202** [comment]
Screenshot (603)

**Comment by Anv3sh** [comment]
Good. Just make the page edges round rather than sharp.

**Comment by Prerna-0202** [comment]
> Good. Just make the page edges round rather than sharp.

At present it is `border-radius: 5px;`.
Can you please tell how much will  be good ??

**Comment by pulkit-30** [comment]
> Good. Just make the page edges round rather than sharp.

I think this can be done while working on issue #11 @Anv3sh

**Comment by dewank07** [comment]
> > Good. Just make the page edges round rather than sharp.
> 
> I think this can be done while working on issue #11 @Anv3sh

yep, let someone else start designing the navbar and start arranging elements.

**Comment by dewank07** [comment]
> Screenshot (603)
> 
> Done!! @dewank07

great !!

**Review by dewank07 — APPROVED** [review]
Great work !!

**Comment by pulkit-30** [comment]
Great 🎉

**Pull request merged**
