### PR TITLE
Modified FAQ,Contact Page Responsive (#1)

### PR DESCRIPTION
**Pull request by RamGoel**
1- Modified FAQ Section (Added Content, Smooth Scroll)
2- Made Contact Page Responsive

### CODE REVIEW

**Comment by dewank07** [comment]
image
@RamGoel check this once

**Comment by pulkit-30** [comment]
Also, run `npx pretty-quick` and force push changes again

**Comment by pulkit-30** [comment]
Screenshot 2022-08-30 at 10 00 26 PM

contact form image overflow...

**Comment by pulkit-30** [comment]
LGTM 🎉 

Great work @RamGoel

**Review by pulkit-30 — APPROVED** [review]

**Pull request merged**
