### PR TITLE
Added Sponsors page

### PR DESCRIPTION
**Pull request by Prerna-0202**
Fixes: #59 

Screenshots:

Screenshot (640)

### CODE REVIEW

**Comment by Prerna-0202** [comment]
@dewank07 @pulkit-30  @jahnvi-gupta

**Review by pulkit-30 — APPROVED** [review]

**Comment by pulkit-30** [comment]
All looks good... just commit these changes 🚀

**Review by pulkit-30 — CHANGES_REQUESTED** [review]

**Comment by Prerna-0202** [comment]
done @pulkit-30

**Comment by pulkit-30** [comment]
GTG 🎉

**Pull request merged**
